name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Test
      working-directory: ./myapp
      run: mvn test 

    - name: Install
      working-directory: ./myapp
      run: mvn install

    - name: Package
      working-directory: ./myapp
      run: mvn package

    - name: Run Application
      working-directory: ./myapp
      run: mvn exec:java
